# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.6
  - 7.0
  - 7.1

install:
  - composer install --ansi --prefer-dist --no-interaction --optimize-autoloader --no-progress
