name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [7.1, 7.2, 7.3, 7.4]
    name: PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug

    - name: Lint
      run: find . -name \*.php -exec php -l "{}" \;

    - name: Install Dependencies
      run: composer install --ansi --prefer-dist --no-interaction --optimize-autoloader --no-progress

    - name: Test
      run: phpunit tests
